name: "Mainsail HASSIO"
description: "Frontend for Mainsail"
version: "1.0.2"
slug: "mainsail"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
# ingress: true
# ingress_port: 8080
ports:
  8080/tcp: 8080