name: "Mainsail HASSIO"
description: "Frontend for Mainsail"
version: "1.0.5"
slug: "mainsail"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
webui: [PROTO:option_name]://[HOST]:[PORT:8080]/
ingress: true
ingress_port: 8080
ports:
  8080/tcp: 8080